---
title: "Нормальность распределения"
output:
  word_document:
    reference_docx: 'r-lang-template-2.dotx'
params:
  json_file:
    value: x
  html_format:
    value: x
  desc_file:
    value: x
---

```{r, setup, include=FALSE, warning=FALSE, error=FALSE, echo=FALSE, cashe=TRUE}
```

```{r all, results='hide', warning=FALSE, error=FALSE, echo=FALSE, cashe=TRUE}
  ######################
  #ВАЖНО!!!! Косяки текущей версии скрипта
  #1. Если нет значимых различий получается отсутсвие таблицы - это неверно!
  #2. Есть только 1 значимая корреляция то таблица строится не хочет, что тоже неверно!
  #3. Сделать возможность перелючения показывать только значимые различия или все 
  ######################

  if(!exists("include_libraries", mode="function")) source("../functions.R")
  if(0) source("calc_functions.R")
  if(!exists("calc_prepare_data", mode="function")) source("../w_z.R")

  include_libraries()

  data <- rjson::fromJSON(file = params$json_file)
  HTML_FORMAT <- params$html_format
  desc_file <- ifelse(params$desc_file == 'None', F, params$desc_file)

  # for test 
  # HTML_FORMAT <- 'short'
  # data <- rjson::fromJSON('{"group_name_1":"g1","group_count_1":3,"group_data_1":{"Шкала 1":{"1":76,"2":87,"3":786},"Шкала 2":{"1":76,"2":6,"3":876}}}')

  GROUP_VAR <- 'Группа'

  #выбор нужно метода корреляции
  METHOD_NAME <- "w"
  # METHOD_NAME <- "z"

  #определяю что за критерий будет использовать и сохраняю его название и букву обозначения
  stat_name <- "Шапиро-Уилка"
  stat_sumbol <- "W"

  MAIN_DF <- calc_prepare_data(data, GROUP_VAR)
```

```{r child='../w_z.Rmd'}
```
